package br.edu.unidavi.oscar.model;

import java.io.Serializable;
import java.util.Objects;
import java.util.Set;

/**
 * Model class of categoria.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Categoria implements Serializable {

    
    private static final long serialVersionUID = 1L;

    
    private Integer catCodigo;

    
    private String descricao;

    
    private Set<Indicacao> indicacaoSet;

    
    public Categoria() {
    }

    public Categoria(Integer catCodigo, String descricao) {
        this.catCodigo = catCodigo;
        this.descricao = descricao;
    }

    public Integer getCatCodigo() {
        return catCodigo;
    }

    public void setCatCodigo(Integer catCodigo) {
        this.catCodigo = catCodigo;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Indicacao> getIndicacaoSet() {
        return indicacaoSet;
    }

    public void setIndicacaoSet(Set<Indicacao> indicacaoSet) {
        this.indicacaoSet = indicacaoSet;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 97 * hash + Objects.hashCode(this.catCodigo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Categoria other = (Categoria) obj;
        return Objects.equals(this.catCodigo, other.catCodigo);
    }  
}
