package br.edu.unidavi.oscar.model;

import java.io.Serializable;
import java.util.Objects;

/**
 * Model class of vencedor.
 *
 * @author generated by ERMaster
 * @version $Id$
 */
public class Vencedor implements Serializable {

    /**
     * serialVersionUID.
     */
    private static final long serialVersionUID = 1L;

    /**
     * pk
     */
    private VencedorPk pk;
    
    /**
     * pessoa
     */
    private Pessoa pessoa;

    /**
     * Constructor.
     */
    public Vencedor() {
    }

    public Vencedor(VencedorPk pk, Pessoa pessoa) {
        this.pk = pk;
        this.pessoa = pessoa;
    }

    public VencedorPk getPk() {
        return pk;
    }

    public void setPk(VencedorPk pk) {
        this.pk = pk;
    }

    public Pessoa getPessoa() {
        return pessoa;
    }

    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 19 * hash + Objects.hashCode(this.pk);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Vencedor other = (Vencedor) obj;
        return Objects.equals(this.pk, other.pk);
    }

}
